### ISSUE TITLE
Feature Request: Add Crossfade Effect for Background Image Transitions

### ISSUE THREAD

**Issue by Sans3108** [Astromations/Hazy#1]
Currently, the background image snaps to the next one instantly when the song changes. By implementing a crossfade effect, the transitions would be smoother and provide a better user experience. It would probably be a nice addition if the crossfade effect duration also matched with the crossfade setting for audio but I'm not exactly sure if it's possible and easy to do so.

**Comment by Astromations** [comment]
That is an excellent idea. I'll see what I can do.
