### ISSUE TITLE
Hazy not working on Spicetify update

### ISSUE THREAD

**Issue by madtitan1712** [Astromations/Hazy#108]
![Screenshot 2024-06-21 100049](https://github.com/Astromations/Hazy/assets/96382688/8c28b901-f008-4df4-ada4-19972aee16a5)All we get is a black screen on the background and the Hazy settings were not available at the home page. Both spotify and Spicetify were updated.

**Comment by Donaldino7712** [comment]
can confirm that this happens, here are the errors when opening the console
![obraz](https://github.com/Astromations/Hazy/assets/100215778/dbc48eda-841b-49ee-863a-2b973d5abc92)

**Comment by ambareeshav** [comment]
same here, i just get a black background, also the small icon on the top bar to edit hazy settings has gone missing

**Comment by IgorCentofante** [comment]
![image](https://github.com/Astromations/Hazy/assets/85705273/21b44e5e-03ef-4cb0-a546-2da5603e232c)

Yup
 I tried to manually install the theme, but to no avail.

**Comment by Astromations** [comment]
Yeah this is a problem with the latest update. It breaks a bunch of javascript. It might take me a while to fix so for now I recommend downgrading to 1.2.39 for a little while:

https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.39.578.g0ea3f38b-107.exe

**Comment by Zuntie** [comment]
> Yeah this is a problem with the latest update. It breaks a bunch of javascript. It might take me a while to fix so for now I recommend downgrading to 1.2.39 for a little while:
> 
> https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.39.578.g0ea3f38b-107.exe

Should be fixed in #109 for now.

**Comment by madtitan1712** [comment]
Its working now. I'll close the ticket ??

**Comment by SKDemon820** [comment]
>Also, How do you guys get the dev tools open for the spotify desktop app ?

run `spicetify enable-devtools` then just right click anywhere in the app to show the menu where you can open them.  If it doesn't work the first time just rerun the command to reload the app again.
