### ISSUE TITLE
Is Hazy autoupdating, or do I need to reinstall?

### ISSUE THREAD

**Issue by JustSxm** [Astromations/Hazy#114]

**Comment by Astromations** [comment]
Hazy auto-updates. Are you experiencing any issues?

**Comment by JustSxm** [comment]
I have no idea if it comes from Hazy, but my spotify crashes sometimes and Im trying to understand where it comes fromSamLe 10 juill. 2024 à 11:55 a.m., Astromations ***@***.***> a écrit :﻿
Hazy auto-updates. Are you experiencing any issues?

**Comment by rohitrw07** [comment]
not being able to use custom bgs

**Comment by Astromations** [comment]
> I have no idea if it comes from Hazy, but my spotify crashes sometimes and Im trying to understand where it comes fromSamLe 10 juill. 2024 à 11:55 a.m., Astromations ***@***.***> a écrit :﻿
> 
> Hazy auto-updates. Are you experiencing any issues?
> 
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

If I were you I'd take a look at my other extensions. It could be a performance issue, version mismatch, or another plugin that's causing the crashes. 

Please go to the three dots in the top right > Help > About Spotify and send me the full expanded screenshot of your versions and installed plugins.

**Comment by Astromations** [comment]
> not being able to use custom bgs

Ideally, try and use a link instead of a locally saved image. Spotify memory is volatile so it's best to load the image from online.

**Comment by JustSxm** [comment]
Spotify for Windows (64 bit)
1.2.41.434.g39a25e2c
Spicetify v2.36.15
Theme: Hazy
Extensions: made-for-you-shortcut.js, immersiveView.js, cat-jam.js, spicetify-ai-playlist-images.js, volumePercentage.js, spotifyGenres.js, beautiful-lyrics.mjs
Custom apps: marketplace, lyrics-plus

**Comment by JustSxm** [comment]
Spotify seems to have updated and broken the Theme during the night for me. Its all pitch black now
