### ISSUE TITLE
Hazy image upload not working

### ISSUE THREAD

**Issue by Uselessskull213** [Astromations/Hazy#115]
When I try to upload an image as the background of Hazy, it works, but, after that, I cannot upload it anymore until I shut down and restart my pc. What is causing this? I have Custom background on, I have tried changing a bunch of settings and deleting the url, but it just wont work.

**Comment by Astromations** [comment]
That is to say the image doesn't load even if you use a link. Please try uploading your image to Imgur and using that link.

**Comment by DarkPhantom2605** [comment]
> When I try to upload an image as the background of Hazy, it works, but, after that, I cannot upload it anymore until I shut down and restart my pc. What is causing this? I have Custom background on, I have tried changing a bunch of settings and deleting the url, but it just wont work.

same problem here, but in my case the custom background doesnt work at all. only the song banners are made into background but when i try to upload a image from my pc or imgur, it doesnt work at all. instead its just a full black theme
