### ISSUE TITLE
Hazy doesn't allow grid view on artist albums

### ISSUE THREAD

**Issue by Blue-Meanie** [Astromations/Hazy#116]
Like the title states, the hazy theme doesn't have grid view, only list view. I really like this theme but I hate having to scroll down so much when looking for a specific album

![image](https://github.com/user-attachments/assets/cd2f3294-ab5e-4462-9e99-61f4c4dd3375)

**Comment by Astromations** [comment]
Just fixed this. Thanks for the heads up.
