### ISSUE TITLE
Marketplace is missing

### ISSUE THREAD

**Issue by riskaya** [Astromations/Hazy#12]
I can't find my marketplace. I tried reinstalling it and updating my spicetify but it won't reappear.

**Comment by riskaya** [comment]
![image](https://github.com/Astromations/Hazy/assets/137668478/a197946b-a15b-4734-9628-bf264a17377e)

**Comment by Astromations** [comment]
Your Spotify and Spicetify are both out of date. 
Here is the latest version of Spotify:
https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.14.1149.ga3ae422d-1027.exe

Run `spicetify upgrade` in terminal to upgrade Spicetify. This might also fix your background image issue.

**Comment by riskaya** [comment]
Oh okay. I'll try

**Comment by riskaya** [comment]
It worked, thanks

**Comment by Astromations** [comment]
Cool
