### ISSUE TITLE
Library disappears when browsing

### ISSUE THREAD

**Issue by BennyKanthi** [Astromations/Hazy#122]
![Screenshot 2024-08-16 000305](https://github.com/user-attachments/assets/d20afdad-ec30-48df-85cb-4f2a4765ae90)

Library disappears when browsing as you can see in the above screenshot. You can fix it by squishing the library then re-streching it but it's quite annoying.

Thanks!
Hope we can get a fix!

**Comment by BennyKanthi** [comment]
![Screenshot 2024-08-16 000548](https://github.com/user-attachments/assets/85c79c05-4494-4187-bd50-dc64d882489c)
Here's a better screenshot!

**Comment by Astromations** [comment]
This looks like an incompatibility with the layout you're using. For now I recommend changing this setting to "control" under experimental settings.

![image](https://github.com/user-attachments/assets/141b7360-ccd4-458a-909f-b0dbf8918373)

**Comment by eyespyy** [comment]
the marketplace option disappeared, not able to change themes or add something new. Stuck
![Screenshot (25)](https://github.com/user-attachments/assets/f6dd388a-5837-44f3-9940-60ca70a46ef3)

**Comment by Astromations** [comment]
Hey. Sorry for the late response. Any developments on that issue?
