### ISSUE TITLE
Extreme lags

### ISSUE THREAD

**Issue by DADA30000** [Astromations/Hazy#126]
Uploading kek.mp4…

**Comment by DADA30000** [comment]
oops

https://github.com/user-attachments/assets/455a3b57-2278-44c7-b208-db41243bed91

**Comment by DADA30000** [comment]
It's HEVC video so it won't load in firefox

**Comment by Astromations** [comment]
Interesting. Hazy is generally a pretty intensive theme since it blurs everything and all. Try toggling your hardware acceleration in settings.

**Comment by nomd346** [comment]
i have this issue too

**Comment by DADA30000** [comment]
I figured out that this is issue with the spotify itself, I think it's happening when there are animations on screen, even without spicetify, so it's not related to this theme, closing this issue
