### ISSUE TITLE
Visual Bugs with banners in playlist and artist page

### ISSUE THREAD

**Issue by Parthiv-Soni** [Astromations/Hazy#127]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/aea39d83-4c5c-409c-9081-6da004901296">
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/8af05e8e-7e1f-4ab3-913c-faa05793d584">

also the top strip isn't translucent too

**Comment by Astromations** [comment]
Thanks for the notice. I just pushed a fix that should fix these issues. There'll likely be a problem with the transparent window controls though. I'm working on a fix for that.
