### ISSUE TITLE
My background can't be displayed

### ISSUE THREAD

**Issue by OOZYUAN** [Astromations/Hazy#129]
I don't know if I set it wrong somewhere... My background never showed up, it was always black, but I had selected a
<img width="1080" alt="微信图片_20241028111547" src="https://github.com/user-attachments/assets/d61fd233-b09a-43af-b48c-f9def7f1690a">
<img width="324" alt="微信图片_20241028111557" src="https://github.com/user-attachments/assets/79f4e836-1dba-4b5a-a2c2-d627b64472b5">
 photo

**Comment by Mr-Shovel1** [comment]
Try uploading it as an Imgur link ex: 

https://imgur.com/BISPpuN.png

**Comment by OOZYUAN** [comment]
> Try uploading it as an Imgur link ex:
> 
> https://imgur.com/BISPpuN.png

thx! but it still doesn't work...
![Uploading image.png…]()

**Comment by OOZYUAN** [comment]
![Uploading 微信图片_20241101161422.jpg…]()

**Comment by Necrot1ccc** [comment]
After uploading it to Imgur, make it public, open the image in a new tab, then use the link of the new tab, the link shouldn't have an **/a/** in the middle of the link, an example being:
Incorrect Link: https://imgur.com/ifealqR
Correct Link: https://i.imgur.com/ifealqR.jpeg

**Comment by OOZYUAN** [comment]
> After uploading it to Imgur, make it public, open the image in a new tab, then use the link of the new tab, the link shouldn't have an **/a/** in the middle of the link, an example being: Incorrect Link: https://imgur.com/ifealqR Correct Link: https://i.imgur.com/ifealqR.jpeg

ok! thank u !  solved!
