### ISSUE TITLE
Side panel bottom/top dim persists after scrolling to top/bottom

### ISSUE THREAD

**Issue by Tetrapak0** [Astromations/Hazy#13]
See how the bottom-most item is slightly dimmed/faded?
![image](https://github.com/Astromations/Hazy/assets/112382253/acccab1b-5506-49b1-8ac0-c4c025ad8e98)
Same with the text on the right panel:
![image](https://github.com/Astromations/Hazy/assets/112382253/46f9001e-a6a9-4f24-a7e6-9da887c5fade)

Spotify Version: 1.2.14.1149
Spicetify Version: v2.20.1
Hazy last update: 24th June 24th, 2023
Zoom level: 90%

Also there is a minimise, restore and close button placeholder behind the buttons themselves. (The white rectangle in the second image)

**Comment by Astromations** [comment]
Currently working on a fix for the window control background issue. I'll add fixing the bottom fade to the list. Thanks for drawing my attention to it.

**Comment by Astromations** [comment]
Launched fixes for both of these. Reload your Spotify client and these should hopefully be fixed.

**Comment by Tetrapak0** [comment]
Marketplace still says last updated on 24th of June. Maybe it needs some time. The placeholder is fixed, though the fade is stil there. On the left sidebar it's less prominent, on the right it's the same. Again, maybe the change wasn't yet registered in spicetify.

**Comment by Astromations** [comment]
Try updating now

![image](https://github.com/Astromations/Hazy/assets/80211195/eeecc2ac-e521-4a5e-9384-546fdcccc5ec)
