### ISSUE TITLE
Fullscreen doesnt work properly

### ISSUE THREAD

**Issue by mishayleMoodley** [Astromations/Hazy#130]
![image](https://github.com/user-attachments/assets/641c0051-0214-45c2-a134-087634d94b2a)

the album cover and media controls aren't aligned properly. the progress bar also doesn't work :(

**Comment by Astromations** [comment]
This looks like an issue with the Beautiful Lyrics extension. Without Hazy active I'm experiencing the same issue with the extension installed.
