### ISSUE TITLE
custom background error

### ISSUE THREAD

**Issue by jayjack24** [Astromations/Hazy#136]
every time i add a link and/or picture of my own, it just turns the whole background to black, and yes I do have "custom background" turned on, but it still just turns everything to black instead of the background I chose

**Comment by Astromations** [comment]
Could you give me an example of a link you're using. For example, if it's Imgur, there's a specific format you're supposed to use.

**Comment by Astromations** [comment]
Here's what you want: https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg

Next you want the link to an image, right click on the image itself and click on "Copy Link"

**Comment by jayjack24** [comment]
okay thank you that worked but one last thing, how did u get the image to come up as that type of link? (the image by itself basically) Everytime I go to a picture I copy and paste it and the same black background thing happens. like am I supposed to download the image first?

**Comment by jayjack24** [comment]
it worked, thank you for the help

**Comment by jayjack24** [comment]
ok that worked, thank you. But can u tell me for future reference which format im supposed to use? bc I copy/pasted another image into it and the black background thing happened again.
