### ISSUE TITLE
[BUG] Now playing overlapping lyrics full view

### ISSUE THREAD

**Issue by iamxyntho** [Astromations/Hazy#14]
# Description of the bug
Whenever you open the lyrics full view from the now playing view and click the expand icon on the cover art, it overlaps the lyrics.

# Steps to reproduce the bug
## 1. Open now playing window
![image](https://github.com/Astromations/Hazy/assets/79999919/d3556aa0-db1f-4fae-adf5-1ebfb85650b5)

## 2. Click on "Open in cinema mode" in the lyrics area 
<img width="193" alt="image" src="https://github.com/Astromations/Hazy/assets/79999919/189e859e-6f92-4f23-841e-d4e07ea13535">
<img width="960" alt="image" src="https://github.com/Astromations/Hazy/assets/79999919/2172bca9-0a90-4fda-a29c-193f79edc8f1">

## 3. Click on expand in the album art in the left area 
<img width="304" alt="image" src="https://github.com/Astromations/Hazy/assets/79999919/cef49a35-c976-4a13-8076-63f46393ac93">

And this is how it'll end up looking 
<img width="960" alt="image" src="https://github.com/Astromations/Hazy/assets/79999919/9475e748-d5ea-4c16-8544-8f6c07e66710">

**Comment by Astromations** [comment]
I see. I'll look into this.

**Comment by iamxyntho** [comment]
Thank you.
