### ISSUE TITLE
Background Image Won't Apply

### ISSUE THREAD

**Issue by xBenjo** [Astromations/Hazy#15]
What is the max size image I can use? I have tried adding 1080p image through imgur and direct storage and neither would load. Love the theme :)

**Comment by Astromations** [comment]
Please send your Spotify and Spicetify versions. They are under this menu.

![image](https://github.com/Astromations/Hazy/assets/80211195/02af3b4a-2f5f-4c93-b991-4b802337144b)

**Comment by xBenjo** [comment]
Spotify for Windows (64 bit)
1.2.14.1149.ga3ae422d
Spicetify v2.20.3

**Comment by Astromations** [comment]
I see. Send me the link to the image you're trying to use.

**Comment by xBenjo** [comment]
https://imgur.com/gallery/vplDUty

**Comment by Astromations** [comment]
Try this link:
https://i.imgur.com/7JhCnuS.png

**Comment by xBenjo** [comment]
Thank you
