### ISSUE TITLE
[SUGGESTION] Round buttons

### ISSUE THREAD

**Issue by thegoldknight** [Astromations/Hazy#16]
Would it be possible to add round buttons like the original Spotify theme and have a setting to toggle on/off?

**Comment by Astromations** [comment]
The rounded square buttons were an opinionated decision, as is every other features of Hazy. I might add an option to change rounding in the future but for now, it's a feature so specific that I don't think it deserves a place in settings. I'd advise you to just change the ```button-border``` variable in the css but that might affect other element that'd require custom fixes.
