### ISSUE TITLE
Bring back artist banner background

### ISSUE THREAD

**Issue by thegoldknight** [Astromations/Hazy#17]
Before, the artist banner would appear at the top of the artist's page, and then move to the background but still stay visible as you scroll down. Now the artist banner just fades into the background instead of staying visible. Is it possible to have this as a toggle option, as some may really like the option and some may not?
 
<img width="1017" alt="image" src="https://github.com/Astromations/Hazy/assets/135397968/b4466474-5a9c-41b5-bc82-b2b8c899e664">

**Comment by Astromations** [comment]
Again, that's a feature a little too specific to warrant a place in the settings menu. If you want to remove it however, you can make a Powershell installation and switch out the content of the repo's ```app.css``` in your ```user.css``` and change the text 
```var(--artist-fade)``` to ```1``` on about line 935. 

![image](https://github.com/Astromations/Hazy/assets/80211195/a14f8e61-2e38-4da9-a045-07c84e87fcc9)
