### ISSUE TITLE
Faded title bar and cancel button of the right sidebar (Friend activity & Detailed view)

### ISSUE THREAD

**Issue by donmesswthme** [Astromations/Hazy#18]
![image](https://github.com/Astromations/Hazy/assets/85218844/4296cdce-92e6-4c92-9d51-6c1356bdccdc)
![image](https://github.com/Astromations/Hazy/assets/85218844/bebde9ef-b2e0-40e5-b214-631f7e56c0eb)

the title bar and the cancel button of both the details and friend activity sidebar are faded. Can you remove scrolling reaches the top? Instead of the fade going all the way and blocking the title and cancel button when it's at the top.

**Comment by Astromations** [comment]
There should be padding on the top of the sidebar to prevent this. Are you using any extensions or snippets that may interfere with it. This is what it looks like on my end: 

![image](https://github.com/Astromations/Hazy/assets/80211195/b3d1d976-6b1c-4dfd-9e52-a0b3f99b7919)

**Comment by donmesswthme** [comment]
https://github.com/Astromations/Hazy/assets/85218844/f9a0eb00-0421-443e-b5d3-464cc9f02c0b

I tried removing every extension and snippet I installed, no effect still... TIll I removed the theme itself in the video. I'm not sure what is affecting it...

**Comment by iamxyntho** [comment]
@Astromations I am also getting this all the time, the padding isn't applied.

**Comment by Astromations** [comment]
I removed a custom padding rule. Try reloading and see if it works now. Xyntho, if you get a spare moment, try checking what specific css rule is causing the problem because cause I can't replicate the issue.

**Comment by donmesswthme** [comment]
![image](https://github.com/Astromations/Hazy/assets/85218844/c8a8728a-5047-4057-a452-9d2cf7609f26)
Still experiencing the problem...

**Comment by Astromations** [comment]
Please send your version and extension/custom app list. It's under this menu:

![image](https://github.com/Astromations/Hazy/assets/80211195/c5b17d70-3de1-4268-a034-d54f272007fe)

Send a screenshot of this screen:
![image](https://github.com/Astromations/Hazy/assets/80211195/ca948fe3-e677-45c0-b225-6f35bc891102)

**Comment by donmesswthme** [comment]
![image](https://github.com/Astromations/Hazy/assets/85218844/3587e098-bd64-40aa-ae6d-60c4127ef6bd)

**Comment by Astromations** [comment]
I've just pushed a change that should make it so there's no fade when you're scrolled all the way up on the right sidebar. Reload whenever you get the chance and see if it fixes this issue.

**Comment by Armagxtten** [comment]
hi, i just wanted to say that ever since the new update the top of the title bar is strangely unfaded and unblended and when you scroll a bit more down it then starts to become faded, before it looked perfectly fine on my end 

![image](https://github.com/Astromations/Hazy/assets/71872569/43ff2fb0-3a64-45fa-9327-8bfbc93b3d29)
![image](https://github.com/Astromations/Hazy/assets/71872569/f0f4e388-d7c2-418e-b824-c8ba70887f33)

**Comment by donmesswthme** [comment]
![image](https://github.com/Astromations/Hazy/assets/85218844/6c9d79ac-ae84-4c15-aae9-0b5a6e351e7f)
![image](https://github.com/Astromations/Hazy/assets/85218844/df502627-0f6f-480f-b8b4-932bd67c8b8a)
working so fine. thank you so muchh

**Comment by donmesswthme** [comment]
![image](https://github.com/Astromations/Hazy/assets/85218844/4c38923c-3aa4-484d-a27c-7789a0a177b5)
the problem of super-long playlist titles being cut off still need to be fixed... only happens to 3+ rows of titles. 2 rows and below are working fine

**Comment by Astromations** [comment]
> hi, i just wanted to say that ever since the new update the top of the title bar is strangely unfaded and unblended and when you scroll a bit more down it then starts to become faded, before it looked perfectly fine on my end
> 
> ![image](https://user-images.githubusercontent.com/71872569/251599163-43ff2fb0-3a64-45fa-9327-8bfbc93b3d29.png) ![image](https://user-images.githubusercontent.com/71872569/251599179-f0f4e388-d7c2-418e-b824-c8ba70887f33.png)

That's because its fading the background the Beautiful Lyrics extension adds. I'll look into a fix.

**Comment by Astromations** [comment]
> ![image](https://user-images.githubusercontent.com/85218844/251621388-4c38923c-3aa4-484d-a27c-7789a0a177b5.png) the problem of super-long playlist titles being cut off still need to be fixed... only happens to 3+ rows of titles. 2 rows and below are working fine

Changed some font sizes. Should be a tentative fix. If the issue persists, please reduce the size of one of your sidebars.

**Comment by Armagxtten** [comment]
@Astromations issue seems to be fixed now, thanks!

![image](https://github.com/Astromations/Hazy/assets/71872569/9ffea5ae-b556-46e1-8138-6504d98be254)

**Comment by Astromations** [comment]
Great. @donmesswthme I'm gonna close the issue now. Adjusting sidebar widths should be a quick fix your playlist title problem if my changes didn't already remedy it. If anything else comes up, go ahead and put up a new issue.
