### ISSUE TITLE
lyrics likes to escape the small lyrics box and overlap with everything 

### ISSUE THREAD

**Issue by DeathLuck578** [Astromations/Hazy#19]
![Screenshot 2023-07-04 115348](https://github.com/Astromations/Hazy/assets/137679577/5b695ec9-e218-41ca-8ae6-fcccdc3ddc61)

**Comment by Astromations** [comment]
Please go into this menu:
![image](https://github.com/Astromations/Hazy/assets/80211195/bb3d63e2-bd8f-4e69-9caa-da5fe74b989b)

and send a screenshot of this:
![image](https://github.com/Astromations/Hazy/assets/80211195/f59295d9-8f21-4999-8d07-74e9835b181a)

**Comment by Astromations** [comment]
I'm having trouble replicating the issue but I've fixed some css which might have caused it. Hopefully you shouldn't see the problem again but I can't be sure. Comment again if you do. Also never mind about your ```About Spotify```. It seems to be an issue across versions.

**Comment by DeathLuck578** [comment]
ok it's good now
