### ISSUE TITLE
Empty spot in top right corner on macOS

### ISSUE THREAD

**Issue by bjwielgosz** [Astromations/Hazy#2]
<img width="1440" alt="Screenshot 2023-06-05 at 21 51 54" src="https://github.com/Astromations/Hazy/assets/72981011/0199a6ea-3dbb-4ba2-a3dc-85073e046fd3">
<img width="1136" alt="Screenshot 2023-06-05 at 21 54 41" src="https://github.com/Astromations/Hazy/assets/72981011/739a0d13-0b96-4f11-bcbd-3db2feef2d39">

On macOS, there is an empty spot left after Windows buttons. Doesn't seem to appear in other themes.

**Comment by Astromations** [comment]
On it!

**Comment by Astromations** [comment]
Just pushed something that should fix this. Reinstall Hazy from Marketplace and get back to me whenever you can about whether or not the bug is fixed.

**Comment by bjwielgosz** [comment]
It's fixed now, thanks a lot!
