### ISSUE TITLE
no marketplacem+ no playlists

### ISSUE THREAD

**Issue by wonpilgirly** [Astromations/Hazy#21]
i cant access the marketplace anymore nor can i go to any of my playlists :( the whole left bar is just empty

**Comment by Astromations** [comment]
Can you send a screenshot of the window. And if you still have access to it, click this button:

![image](https://github.com/Astromations/Hazy/assets/80211195/42fbc989-04ac-4adc-9f81-1851a6710031)

and send a screenshot of the information on this screen. 

![image](https://github.com/Astromations/Hazy/assets/80211195/5ab211ca-b6ea-4535-8f00-495e9f1f2623)

**Comment by Astromations** [comment]
Gonna go ahead and close this. If you're still suffering from this issue, try updating:
https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.15.828.g79f41970-1030.exe
