### ISSUE TITLE
hazy theme not working from Spicetify

### ISSUE THREAD

**Issue by ohmlikepopcorn** [Astromations/Hazy#24]
The hazy theme not having a market place section from Spicetify pls help

**Comment by Astromations** [comment]
Is this specifically a problem with Hazy? Did you install Hazy through Powershell or through marketplace. Please go to this drop down and send me the information that shows up under "About Spotify":

![image](https://github.com/Astromations/Hazy/assets/80211195/4125b5ae-f167-41c2-ad1b-a6fe3318d7b2)

For now, you could try reinstalling marketplace with this Powershell command:
```Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.ps1" | Invoke-Expression```
