### ISSUE TITLE
[QUESTION] Spotify background images used in preview screenshots

### ISSUE THREAD

**Issue by xchrl** [Astromations/Hazy#26]
Hello, is it possible to link the background images of Spotify that were used in the preview screenshots in the README file? More specifically, I'd like to know which background images were used in the `hazy_home.png` and `hazy_play.png` files in the repository. Asking because I really took a liking to them and I wasn't quite able to get any results when reverse image searching for them on the internet. I'd like to use them as my own Spotify backgrounds. Sorry if this is the incorrect way of asking a question in this type of matter, but I didn't really see any other way of asking questions like this other than the issue tracker. I hope you can understand :)

**Comment by Astromations** [comment]
I got them off Reddit about a month ago. They'd be buried under a ton of posts by now. I'll try looking for them but I can't make any promises.

**Comment by Astromations** [comment]
I have since found the use used in ```hazy_home.png```, but not ```hazy_play.png```.

https://i.redd.it/e9vgzh9o4v1b1.jpg
