### ISSUE TITLE
Interface gets expanded to the right when resizing left sidebar on full-screen lyrics panel

### ISSUE THREAD

**Issue by victorbnl** [Astromations/Hazy#27]
https://github.com/Astromations/Hazy/assets/39555268/e3390a11-4cc6-4719-b914-43310fb0b381

**Comment by Astromations** [comment]
Thanks for notifying me. I'll start working on a fix.

**Comment by Astromations** [comment]
Issue should have been fixed with a Pull Request I merged a while back. Please check that you're not still experiencing the error.

**Comment by victorbnl** [comment]
I can confirm this is fixed indeed!
