### ISSUE TITLE
Very High GPU USAGE WHILE PLAYING SONGS

### ISSUE THREAD

**Issue by Hrushal-Nikhare** [Astromations/Hazy#29]
while using the hazy theme my gpu usage spikes up to from 1-3% to 85%

**Comment by Hrushal-Nikhare** [comment]
Note: I have tried other themes such as bloom or galaxy and both of them get GPU usage to 10% at max

**Comment by Hrushal-Nikhare** [comment]
![image](https://github.com/Astromations/Hazy/assets/82302201/b0c39dc8-fff6-421a-82a6-3b99276b8f9d)
![image](https://github.com/Astromations/Hazy/assets/82302201/3ee2ffec-9225-4b5a-95d2-96e81ece7be7)

**Comment by Astromations** [comment]
Do you happen to have a particularly high blur in settings? In any case, try turning it down or off. 

Hazy uses blur in nearly every part of the UI so it's quite GPU intensive.

**Comment by Hrushal-Nikhare** [comment]
checking

**Comment by Hrushal-Nikhare** [comment]
let me try reinstalling everything

**Comment by Hrushal-Nikhare** [comment]
removing blur did not work

**Comment by Hrushal-Nikhare** [comment]
im getting ratelimited

**Comment by Astromations** [comment]
What graphics card are you using?

**Comment by Hrushal-Nikhare** [comment]
Integrated graphics

**Comment by Hrushal-Nikhare** [comment]
![image](https://github.com/Astromations/Hazy/assets/82302201/4a4b1c0b-d41f-402e-8ccb-5412a27220f7)

**Comment by Astromations** [comment]
This could be caused by Hardware Acceleration. You can turn it off here.

![image](https://github.com/Astromations/Hazy/assets/80211195/44dea59d-6e0e-4864-b3a2-d734f32bf402)

This might slow down your client, but its worth a try.

**Comment by Hrushal-Nikhare** [comment]
slower but ig it works
