### ISSUE TITLE
Dont work on New Spotify Update 

### ISSUE THREAD

**Issue by hocy1609** [Astromations/Hazy#32]
![Spotify_fxsj8kDTye](https://github.com/Astromations/Hazy/assets/74152095/7accee2a-67d7-411a-a256-e36d1497e3ea)
![Spotify_0cTjqF4TrN](https://github.com/Astromations/Hazy/assets/74152095/a146f8e7-9d7e-424e-88e5-481c6b93f7e6)

**Comment by Astromations** [comment]
Thanks for the heads up. I'll get on this as soon as possible.

**Comment by Astromations** [comment]
Alright great! I'll go ahead and close the issue now.
