### ISSUE TITLE
Enhanced feature lyrics panel

### ISSUE THREAD

**Issue by kotobuki09** [Astromations/Hazy#33]
Could you make the lyrics panel adjustable, or provide a way to increase the panel size? Some users may prefer to view it in the sidebar and scroll down for more information if needed. [https://i.imgur.com/WxvGQYC.png](https://i.imgur.com/WxvGQYC.png)

**Comment by Astromations** [comment]
As in you'd like to make the lyrics panel taller? I'll put that on the roadmap.

**Comment by kotobuki09** [comment]
Thank you for your suggestion. It's exactly what I needed
