### ISSUE TITLE
WHY THE FUCK ISNT ITWORKING 😭 

### ISSUE THREAD

**Issue by NubCub** [Astromations/Hazy#4]
I CANT HCANGE THE IMAGE TO A LOCAL IMAGE I HOPE YOU DIE OMGGGGG

**Comment by Astromations** [comment]
There are limitations with local images. Not sure why. It has something to do with volatile image size limits. If you insist on a local image, either use another one of smaller size or compress the one you tried. For now, I recommend you host your image somewhere online (Discord or Imgur) and use a url instead. It's far more reliable.

**Comment by awadhh** [comment]
The theme is just wow, it got everything! Thank You!
