### ISSUE TITLE
Custom Wallpaper backround not working

### ISSUE THREAD

**Issue by xKilixn** [Astromations/Hazy#43]

**Comment by Astromations** [comment]
What's your operating system, Spotify and Spicetify version?

**Comment by Kuttesch** [comment]
Same Problem here.
Windows 11 Build:  22635.2841 ni_release
Spotify Version: Spotify for Windows 1.2.26.187.g36b715a1
Spicetify Version: v2.28.0

**Comment by Astromations** [comment]
Are you trying to use an image saved on your computer or a link? Also, do you have Hazy installed through the marketplace or on your PC itself?

**Comment by Kuttesch** [comment]
Yeah i tried using an image saved locally.
I installed Hazy trough the marketplace, bc i hopped trough some of the newer Themes.

**Comment by Astromations** [comment]
Try using a link to the image. Its file size may be too big.

**Comment by Kuttesch** [comment]
When i try it with a link it works perfectly fine, so i guess its the size of the picture?
The size of the file is 180KB if it helps you in any way

**Comment by Astromations** [comment]
The file size limit is volatile. I've found its just safer to use a link. Apart from slow loading on occasion, they almost always work. Happy to help.

**Comment by Bageang** [comment]
@Astromations What kind of a link do i need to use exactly? cause ive tried using a google drive link which just ends up showing  a dark background

**Comment by Astromations** [comment]
The type of link that embeds. Not sure about the formal term. But if you can post it on something like Discord and it shows the image instead of the link, it should work.
