### ISSUE TITLE
In "Show All Albums" page text and ui icons covering upper line of album covers

### ISSUE THREAD

**Issue by lionnesquaer** [Astromations/Hazy#46]
Greetings!
As title says. Screenshot attached!
![Снимок экрана 2023-12-20 013753](https://github.com/Astromations/Hazy/assets/39178626/08a966bb-666c-4586-94cf-a82cebb912f1)

In other things all good, very like your theme, thank you!

**Comment by Astromations** [comment]
Just pushed a commit that should fix this. Thanks for the heads up.
