### ISSUE TITLE
Install / Remove extension button in marketplace completely hidden

### ISSUE THREAD

**Issue by lionnesquaer** [Astromations/Hazy#47]
Greetings again!
Thank you for fixing previous issue that i was send. Sorry for disturb you but here is another one.

In Marketpalce any extension or theme Install / Remove button completely hidden beyond profile menu button.

![Снимок экрана 2023-12-21 020036](https://github.com/Astromations/Hazy/assets/39178626/45fa97c5-d7fc-428c-a362-00a2d142b946)

Thank you! and happy holidays!

**Comment by Astromations** [comment]
Fixed in the latest commit. Sorry for the delay.
