### ISSUE TITLE
Custom background

### ISSUE THREAD

**Issue by PeterParker2008** [Astromations/Hazy#49]
How do I choose a custom local image for my background?

I think I gotta choose it from File Explorer. But when I do it, it shows this:
![image](https://github.com/Astromations/Hazy/assets/81066924/5248975e-445a-4ce9-8345-3821ec204f2b)

And applying this results in a solid black theme.

**Comment by cantdecidemyname** [comment]
read this #43

**Comment by PeterParker2008** [comment]
Thank you. I will surely look into it.

**Comment by PeterParker2008** [comment]
Thank you. I will surely look into it.
