### ISSUE TITLE
Long playlist titles getting cut off

### ISSUE THREAD

**Issue by donmesswthme** [Astromations/Hazy#5]
Long playlist titles that use up 2 rows and above of title space got cut in half at the 2nd row
![image](https://github.com/Astromations/Hazy/assets/85218844/56f36aae-6f41-45b5-862b-1cc083073800)
![image](https://github.com/Astromations/Hazy/assets/85218844/5a81f4c4-fccc-45a3-8faf-2749bac66650)
![image](https://github.com/Astromations/Hazy/assets/85218844/ea18a439-2068-465e-9149-702b32c7cefc)
It's very annoying... I hope yall can fix it asap 🫶 But been loving the theme so far, it's the best custom background theme I've found 😍

**Comment by Astromations** [comment]
I'll get on that right away

**Comment by Astromations** [comment]
Should be fixed
![image](https://github.com/Astromations/Hazy/assets/80211195/e67b2274-364b-4d4f-8ded-b7f579157de1)

**Comment by donmesswthme** [comment]
Thank you so much! You were quick to solve it😍
