### ISSUE TITLE
Problem with Beautiful Lyrics

### ISSUE THREAD

**Issue by ScoutKadx** [Astromations/Hazy#51]
![image](https://github.com/Astromations/Hazy/assets/156559624/74cf6aac-2ed6-4b2d-8c24-376fc6d0ba45)
Don't know why it happens. Works with other themes but not Hazy.

**Comment by Astromations** [comment]
Other themes don't make the main view panel transparent. The same arrangement is happening with other themes, it's just that with Hazy, the panel is transparent so you can actually see it. I'll look into fixes but I don't know if they'll be soon.
