### ISSUE TITLE
Background Album Art Not Changing With Next Song

### ISSUE THREAD

**Issue by zero-mindset** [Astromations/Hazy#53]
As the title states, the background isn’t changing with the next song. It’s showing whichever song I first started playing. If I restart the theme, it’ll update but then the same thing happens

I am on Spotify 1.2.30.1131 with Spicetify v2.30.0

This is my favorite theme in the marketplace by far, so I hope an update can correct this behavior. Thanks!

**Comment by Astromations** [comment]
Thanks for your support. I just looked into this and curiously enough, I don't think 1.2.30 has been released in my region, nor is it available in the repository of versions I use for troubleshooting. I'm on 1.2.29.605.g66a43ceb right now and I'm sure the version mismatch is the issue. For now I can't fix the issue without be able to use your version, what I can recommend is temporarily downgrading back to 1.2.29 [x64](https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.29.605.g66a43ceb-1229.exe).

Sorry for the inconvenience. Are you using any other themes, extensions? And what is your operating system? I'm almost certain 1.2.30 broke the feature, but you can never be too sure.

Thanks

**Comment by zero-mindset** [comment]
Hi, thanks for the reply. This issue has happened before, but usually
resolves itself at some point. So, i'm not one hundred percent sure it's
strictly about the Spotify version. But perhaps it is. I've pasted my OS
and extensions below. Let me know if you see anything that stands out. I
will check out the previous Spotify version as well and see if that helps.
Thanks!

Spotify for macOS (Intel)
1.2.30.1131.g8de2fb92
Spicetify v2.30.0
Theme: Hazy / Base
Extensions: hidePodcasts.js, playing-source.js, LuckyLP.js,
imaged-folders.js, fullScreenWrapper.js, CoverAmbience.js,
full-queue-clear.js, QueueTime.js, show-the-genres.prism.js,
sort-plus.prism.js, spoqify-radios.prism.js, star-ratings-2.prism.js,
made-for-you-shortcut.js, quickQueue.js, autoplay-toggle.js, songstats.js,
spicetify-playlist-labels.js, AnonymizedRadios.js,
dist\show-the-genres\prism.js, enhancePlus.js, find-duplicates.js, pip.js,
playRandom.mjs, theme.js
Custom apps: marketplace, lyrics-plus, betterLibrary, stats

**Comment by zero-mindset** [comment]
Just to follow up, the issue still persists even on 1.2.29

**Comment by zero-mindset** [comment]
Sorry to bother you again, but I may have strangely come upon a solution to
my problem. Through a random sequence of events, I ended up needing to
start over with my extensions. Anyway, I ended up noticing that when I
installed an extension named “Toggle Autoplay” it broke the theme
background artwork change. I uninstalled it and it was all working fine
again. Not sure what that could have to do with it, but the theme is
working fine now for me

**Comment by Astromations** [comment]
I see. I'm gonna leave well enough alone and stop fiddling with the issue. Will note "Toggle Autoplay" as a problematic extension though. Thanks!

**Comment by tajito** [comment]
Hi! im having the same problem as op, but i still can´t fix it, i've downgraded to 1.2.29, and i don't got any other extension that this one
Operating system is Spotify for Windows (64 bits), with Spicetify v2.31.0

**Comment by zero-mindset** [comment]
Yeah I had the same issue return with the latest Spicetify v2.31.1 and
Spotify 1.2.31.1203
