### ISSUE TITLE
HAZY ISSUE: Background color extraction doesn't change automatically when the music changes. 

### ISSUE THREAD

**Issue by Yovanjonathan** [Astromations/Hazy#57]
Background color extraction doesn't change automatically when the music changes. 
![Screenshot 2024-02-15 165612](https://github.com/Astromations/Hazy/assets/160119999/1a009e7a-0cd2-4b6e-9610-715ba64b9cd7)
![Screenshot 2024-02-15 165629](https://github.com/Astromations/Hazy/assets/160119999/722cafd1-0945-4c5f-9891-dc203c3d664d)

**Comment by flametopia** [comment]
exact same issue but i think it might be a spotify or spicetify issue coz it happened with another theme ive been using for months today as well as hazy

**Comment by Yovanjonathan** [comment]
> exact same issue but i think it might be a spotify or spicetify issue coz it happened with another theme ive been using for months today as well as hazy

Glad that I'm not the only one.

**Comment by grewanhassan** [comment]
On Linux Fedora (Nobara) - KDE and Arch (Manjaro) - KDE everything works fine. So maybe it's a specific Windows 10/11 problem.

**Comment by alfabeta420** [comment]
> On Linux Fedora (Nobara) - KDE and Arch (Manjaro) - KDE everything works fine. So maybe it's a specific Windows 10/11 problem.

bro wanted to flex he's using linux 💀💀

same issue, it was working fine and the day before yesterday it just broke

**Comment by theliamking** [comment]
Got the same problem. Have to go into the theme settings and click apply for it to switch. Hopefully gets patched soon.

**Comment by tajito** [comment]
I've got the same issue, it's probably bcuz of Spicetify, my Spotify is on 1.2.29 and Spicetify on the latest update

**Comment by Astromations** [comment]
I've finally duplicated the issue. I'm working on a fix right now.

**Comment by Astromations** [comment]
> I've got the same issue, it's probably bcuz of Spicetify, my Spotify is on 1.2.29 and Spicetify on the latest update

Problem is looking worse than I thought. For now, Spotify 1.2.29 and Spicetify 2.31.3 looks stable so please use those in the mean time.

https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.29.605.g66a43ceb-1229.exe

**Comment by theliamking** [comment]
> > I've got the same issue, it's probably bcuz of Spicetify, my Spotify is on 1.2.29 and Spicetify on the latest update
> 
> Problem is looking worse than I thought. For now, Spotify 1.2.29 and Spicetify 2.31.3 looks stable so please use those in the mean time.
> 
> https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.29.605.g66a43ceb-1229.exe

Temporary fix is working, good luck on your patch :)

**Comment by KHOJAH** [comment]
It's actually working fine with me 
just delete spicetfy and spotify and reinstalled both and it worked 
![image](https://github.com/Astromations/Hazy/assets/160655004/6b76d917-d646-4711-b889-a80ce07451a5)

**Comment by CarlosJRPereira** [comment]
> En realidad, está funcionando bien conmigo, solo elimine spicetfy y spotify y reinstaló ambos y funcionó ![image](https://private-user-images.githubusercontent.com/160655004/306393293-6b76d917-d646-4711-b889-a80ce07451a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NjE5MjQsIm5iZiI6MTcwODQ2MTYyNCwicGF0aCI6Ii8xNjA2NTUwMDQvMzA2MzkzMjkzLTZiNzZkOTE3LWQ2NDYtNDcxMS1iODg5LWE4MGNlMDc0NTFhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQyMDQwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGQ1ZjAwZGI3ZmFmN2UzNWExODY5MWNmN2NhMjRhZTliZGMwMzY4OTE1ZmQ1ZjllZDY4ODQ5NjkxNWUyYmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DwP_opz5jthT4Qtapvoc4h-RPJ4PtdnaVHUI6KPq7R8)

Puse a prueba lo que dijo y me funciono también gracias, el único detalle que pude ver es que en mi caso la animación ya no se reproduce, antes había una animación de unos segundos cuando se cambia de canción, ahora ya no.

**Comment by Synthetic-Human** [comment]
Same issue here, on Windows 10

Spotify version: Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.31.3

**Comment by tajito** [comment]
> > I've got the same issue, it's probably bcuz of Spicetify, my Spotify is on 1.2.29 and Spicetify on the latest update
> 
> Problem is looking worse than I thought. For now, Spotify 1.2.29 and Spicetify 2.31.3 looks stable so please use those in the mean time.
> 
> https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.29.605.g66a43ceb-1229.exe

Just wanted to update, it's broken again, even using Spotify's old version

**Comment by SKDemon820** [comment]
> Just wanted to update, it's broken again, even using Spotify's old version

@tajito Are you sure Spotify didn't auto-update?  It's still working for me on a slightly old version (Spotify for macOS (Intel)
1.2.26.1187.g36b715a1)

**Comment by tajito** [comment]
> > Just wanted to update, it's broken again, even using Spotify's old version
> 
> @tajito Are you sure Spotify didn't auto-update? It's still working for me on a slightly old version (Spotify for macOS (Intel) 1.2.26.1187.g36b715a1)

Nope, still on 1.2.29, only thing that i update is Spicetify

**Comment by Astromations** [comment]
You all can upgrade your Spotify and Spicetify versions now. This version combination works fine for me. 

![image](https://github.com/Astromations/Hazy/assets/80211195/b319128a-d6a9-4a61-94e9-9d54749a9599)
