### ISSUE TITLE
Small issue with blocking for the top right buttons 

### ISSUE THREAD

**Issue by ChiefJensen** [Astromations/Hazy#61]
![Screenshot 2024-02-29 143455](https://github.com/Astromations/Hazy/assets/50683237/89428ce1-8655-4c50-a96f-ce846be88377)
Seems to be just a size error since by dragging the window size you can see that its just two transparent things on top of eachotehr

**Comment by Dynamixus** [comment]
Same issue :D

**Comment by Astromations** [comment]
Noticed. I'll see what I can do 👍

**Comment by Astromations** [comment]
Fixed in the latest commit. Thanks for the heads up!
