### ISSUE TITLE
Custom Background

### ISSUE THREAD

**Issue by Kivviiii** [Astromations/Hazy#62]
im unable to change the image to another its stuck on the first one i applied the function of apply also doesnt work.

**Comment by Astromations** [comment]
I'm not able to replicate this. Mind giving me some information on your setup? OS, Spotify and Spicetify version? You can find the latter here: 
![image](https://github.com/Astromations/Hazy/assets/80211195/5ea81a49-8a4f-4640-9348-81a9d678f13f)

**Comment by Kivviiii** [comment]
i just tried some thing and it is changing now i just have to reinstall in which i guess somewhat reset the custom background, i dont no but my problem got solved for now

**Comment by Astromations** [comment]
Mind telling me a little more about your set up? Spotify and Spicetify versions, OS? Btw, the background might appear once you've played a song.

**Comment by lea0o0oo** [comment]
Yeah, it appeared after I played a song.
I am rn on arch linux but this problem also affects windows, all of this on the latest spotify and spicetify versions
