### ISSUE TITLE
Graphical bug

### ISSUE THREAD

**Issue by Sans3108** [Astromations/Hazy#63]
No matter the background, there seems to be a small cutout or some sort of glitch near the window buttons
![image](https://github.com/Astromations/Hazy/assets/39863198/c7ad19b8-713d-47f1-a771-aafcd4364aef)
![image](https://github.com/Astromations/Hazy/assets/39863198/27b0da33-35b9-4abb-98cb-1a1676903c89)
![image](https://github.com/Astromations/Hazy/assets/39863198/c0f6dd1d-299a-4a03-9a2b-4841a89dd0db)

**Comment by Sans3108** [comment]
the most eyeballed screenshots ever, but it shows what I mean

**Comment by Astromations** [comment]
This should have been fixed in the latest commit. Try updating your theme if you have it stored locally, or reload your Spotify window if you have it loaded from Marketplace.

**Comment by Astromations** [comment]
Alright, I just took another look and it seems that I updated everything except the one thing that'd have fixed this. I'll fix this as soon as I can. Thanks for the heads up.

**Comment by Sans3108** [comment]
No problem!

**Comment by Astromations** [comment]
Took a while, but finally got around to fixing this.
