### ISSUE TITLE
everything is black

### ISSUE THREAD

**Issue by FluxDotWOOP** [Astromations/Hazy#7]
as the title says, not sure why :/ tried to install the theme through the app as well as powershell, though no help.
transparency effect is enabled in windows, im on windows 10
![image](https://github.com/Astromations/Hazy/assets/33461275/8f283b77-6c57-4e82-b7b3-ddc91d2ef451)

**Comment by Astromations** [comment]
Go here and send me a screenshot of what shows up. Should be your spotify and spicetify versions.
![image](https://github.com/Astromations/Hazy/assets/80211195/a1bfb661-b313-464e-a998-5273432d4824)

**Comment by FluxDotWOOP** [comment]
![image](https://github.com/Astromations/Hazy/assets/33461275/cfdab84a-b56e-40a2-8490-137ef2c2a4c4)
tried to install it again through powershell the second time and now its fine, i guess something went wrong. thank you though! love the theme

**Comment by Astromations** [comment]
Looks to me that you have it installed both through marketplace and natively, hence the two edit icons. That might cause problems so I'd recommend sticking to one
