### ISSUE TITLE
Unable to use custom backgrounds

### ISSUE THREAD

**Issue by beuh0623** [Astromations/Hazy#70]
I try to add in a custom background, but it stays black. I tried uploading to imgur and then plugging it in but it doesn't work. Is it my version of spotify or some other issue?

**Comment by hbishere** [comment]
What version of Spotify/Spicetify are you using?

**Comment by beuh0623** [comment]
I'm using these versions:
Spotify for Windows (64 bit)
1.2.33.1042.g26c92729
Spicetify v2.36.1

**Comment by Astromations** [comment]
You are not on the latest version of Spotify. Please install [this](https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.35.663.gb699649e-6898.exe) version and check to make sure your Hazy updated if you don't have it installed from Marketplace.

**Comment by Astromations** [comment]
Are you still facing the issue?

**Comment by itsrabikhan** [comment]
Having the same issue on the most recent version.

**Comment by Astromations** [comment]
Just to be sure, please run ```spicetify update```. A new version came out recently. I am unable to replicate the issue, and from what I've seen, outdated versions are the most common culprit.

**Comment by Your-Best-Friend86** [comment]
Hi, I just updated the spicetify and spotify and I also have the issue, black screen when I'm trying to choose the image from the device itself or paste the imgur link
version = 1.2.35.663.gb699649e
with    = 2.36.8

**Comment by hbishere** [comment]
I've been able to replicate this issue with the image linked on the same versions. Additionally the reset button does not appear to work correctly.

**Comment by DiosaDuck** [comment]
theres any fix?

**Comment by Astromations** [comment]
From my testing, this is because the image links to a jpeg. After running the image through a jpeg to png tool and uploading to discord for hosting, it seems to be working just fine. Here's the link:

https://media.discordapp.net/attachments/934861946233159710/1235335871973163018/Dcz9GEu.png?ex=6633ffaf&is=6632ae2f&hm=9158e096edc0a969435f261bfc1eb020cba1dd4738dcdd69878df647f1d85809&=&format=webp&quality=lossless&width=1370&height=662

**Comment by DiosaDuck** [comment]
ill try it
