### ISSUE TITLE
Acrylic background with Mica for Everyone 

### ISSUE THREAD

**Issue by BAD4RO** [Astromations/Hazy#73]
Is there a way to make background fully transparent? I tried to replace the background image with a transparent png file but I received a completely black background, is there a way to make it translucent so that the 'mica' effect is applied through the MFE like my Vencord theme mod?

![image](https://github.com/Astromations/Hazy/assets/51465374/ec32400d-b733-46c3-8452-fb2b588b1197)

**Comment by Astromations** [comment]
Unfortunately there currently exists no way to do this. 

It's definitely a long term goal though.
