### ISSUE TITLE
Content overlaps with banners

### ISSUE THREAD

**Issue by thefakequake** [Astromations/Hazy#74]
I'm not sure if this is intentional behaviour or not, but when scrolling with a full-page banner the page content overlaps with the banner:
![image](https://github.com/Astromations/Hazy/assets/67868381/c1d2e197-fd28-4606-af5a-c76e242380b0)
This could cause a problem if the banner is white, rendering text invisible.

**Comment by hbishere** [comment]
This is a known issue and should hopefully be resolved soon.

**Comment by Astromations** [comment]
I've released some bug fixes. Make sure you're on the latest Spotify, Spicetify and Hazy versions and get back to me on this issue. Thanks.

**Comment by thefakequake** [comment]
All good now, the banner fades into the background as expected and there is no more content overlap. Thank you so much.
![image](https://github.com/Astromations/Hazy/assets/67868381/b006351c-7c6a-44d1-a4c4-46f5d2d881aa)
