### ISSUE TITLE
Album/Playlist name overlap with song list as you scroll down

### ISSUE THREAD

**Issue by n0tPuffer** [Astromations/Hazy#75]
Started using this theme a few days ago and I loved it so far but this has annoyed me a little bit. 

Here is my version of Spotify
Spotify for Windows (64-bit)
1.2.34.783.g923721d9
Spicetify v2.36.2

![image](https://github.com/Astromations/Hazy/assets/20552535/18fb6cc5-ab15-4176-a79c-bcf445a6d39f)

Also, I'm not sure if this is the same issue as above or not but this sort of overlap also occurs on the spicetify's marketplace page, which made it so that I can't click on the search button anymore unless I disable/ uninstall the theme.

![image](https://github.com/Astromations/Hazy/assets/20552535/0cb5d18a-1173-4d4c-be59-000697a49cb3)

**Comment by Astromations** [comment]
Yeah, I've noticed this too. A fix is in the works but I've been a bit busy. In the mean time if it's that annoying, you can downgrade your Spotify until a fix comes out for the latest version. Thanks for enjoying my theme 🙏

**Comment by hbishere** [comment]
https://github.com/Astromations/Hazy/commit/3c737759bd98fe98ea8163077333cc9e316f79bf should fix this issue. Make sure you're running the latest Spotify/Spicetify versions.
