### ISSUE TITLE
Black screen when i click on "Album" see everything

### ISSUE THREAD

**Issue by BepopTea** [Astromations/Hazy#76]
Hi ! I wanted to warn you about this bug when I try to see the albums or singles this is what happens
![image](https://github.com/Astromations/Hazy/assets/98472328/3c87c6f9-2b5a-417d-9771-d7b200888392)

Spotify 1.2.34.783
Spicetify V2.36.4
Last version of Hazy on marketplace
Windows 10 64 bit

**Comment by znicuuu** [comment]
same here
![image](https://github.com/Astromations/Hazy/assets/73033465/91746e63-cafb-4059-b5ca-4080c2d0fc89)

**Comment by Astromations** [comment]
I'm not getting this bug in the latest version. Download it here. 
https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.35.663.gb699649e-6898.exe

**Comment by SKDemon820** [comment]
I'm on Mac not Windows, but it seems to be the same version and it's still happening for me
![Screenshot 2024-04-11 at 11 07 21 PM](https://github.com/Astromations/Hazy/assets/62918850/2a81f61d-3592-4bd6-a419-1cee57250377)
![Screenshot 2024-04-11 at 11 09 53 PM](https://github.com/Astromations/Hazy/assets/62918850/73ea8336-0de5-4193-8824-8f23ce1c5e0b)

**Comment by znicuuu** [comment]
_Spotify für Windows (64 Bit)
1.2.35.663.gb699649e
Spicetify v2.36.4
Theme: Hazy
Extensions: playbarClock.js, quickQueue.js, spicetify-playlist-labels.js, volumePercentage.js, playlist-icons.js, beautiful-lyrics.js, bfs-bundle.js
Custom apps: marketplace, better-local-files, lyrics-plus_

even with updated spotify it isn't fixed for me. Though for me it only happens on the artists discography page. The Page of a specific album is working as intended.

**Comment by Astromations** [comment]
Found the issue. Working on a fix as we speak.

**Comment by BepopTea** [comment]
> Found the issue. Working on a fix as we speak.

Thanks for doing fix quickly !
