### ISSUE TITLE
"Name That Tune" is blacked out (worked before)

### ISSUE THREAD

**Issue by Richm246** [Astromations/Hazy#77]
It works fine without Hazy (and worked great until the recent issues) , so I am wondering it's something you can look into?
![Screenshot_1](https://github.com/Astromations/Hazy/assets/49817782/13ca0192-906e-4a29-b4bb-8e5eb501f320)

Any help would be appreciated.

**Comment by Astromations** [comment]
Should be fixed now

**Comment by Richm246** [comment]
Thank you, I appreciate it
