### ISSUE TITLE
Beautiful Lyrics shifting up and down on Now playing view when hovering over it.

### ISSUE THREAD

**Issue by Devil-8943** [Astromations/Hazy#79]
Whenever I hover over the lyrics of the Beautiful Lyrics extension within the Now playing view the scroll bar moves to the left, which in most cases forces the lyrics to change position and shift up and down. It doesn't happen on any other themes I tested. This is not a huge problem but I would love to see that being fixed :)

**Comment by Astromations** [comment]
Just pushed some bug fixes. Please check to see if this is still an issue.

**Comment by Devil-8943** [comment]
> Just pushed some bug fixes. Please check to see if this is still an issue.

Oh yeah it works perfectly again, thank you for :)
