### ISSUE TITLE
The Marketplace icon is gone

### ISSUE THREAD

**Issue by aleksandra-boop** [Astromations/Hazy#8]
Hi! 
I can't see the Marketplace anymore. I tried changing the theme to SpicetifyDefault via Powershell, tried "spicetify restore backup" too, but the only thing that seems to change are the colours. 
Any help please? 

![image](https://github.com/Astromations/Hazy/assets/78408687/e9bd1427-eac4-4d6b-98ce-5662defdff61)

**Comment by Astromations** [comment]
This seems a like an issue for the main spicetify-cli repo, the marketplace repo or perhaps the Discord server. I can't replicate it so I don't think its a problem with Hazy. From what I've experience however, I'd try closing Spotify and all its sub-services in Task Manager. If upon restart the marketplace hasn't appeared, try running spicetify apply, and if that doesn't work, run the marketplace install script again. 

Again, this is an issue beyond the scope of the theme. If what I suggested didn't work, submit an issue here:
https://github.com/spicetify/spicetify-marketplace

or consult the official Spicetify Discord server:
https://discord.gg/NMkwW438
