### ISSUE TITLE
doesn't show any lyrics

### ISSUE THREAD

**Issue by lolik1124** [Astromations/Hazy#81]
doesn't show any lyrics even if only this plugin is installed
![чиназес](https://github.com/Astromations/Hazy/assets/167940645/e12ac039-e29f-4447-bd79-8d89fc365493)

**Comment by Anirudh0019** [comment]
++ , i got no option for lyrics

**Comment by Astromations** [comment]
I can't seem to replicate this. Please download the latest Spotify version here: https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.36.959.g04bf500c-847.exe

and run ```spicetify update``` to ensure you're on the latest Spicetify.

**Comment by Anirudh0019** [comment]
everything is up to date
![image](https://github.com/Astromations/Hazy/assets/127773678/827bc343-c85d-4580-83f8-035f0ed1d466)

**Comment by Astromations** [comment]
I can't seem to replicate this. You're sure you have nothing else installed? What's your OS and Spotify/Spicetify version. You can check here: 
![image](https://github.com/Astromations/Hazy/assets/80211195/6c30271d-9b33-46fd-89df-00ace9206b43)
