### ISSUE TITLE
black image when using the NCS Visualizer extension together with hazy

### ISSUE THREAD

**Issue by schnuckee** [Astromations/Hazy#82]
basically what the title says, picture is attached
ive had this issue for about 2 weeks now id say, before everything was working perfectly fine, the visualizer extension works fine when not using hazy so i assume this is an issue with the theme
![prev](https://github.com/Astromations/Hazy/assets/99971689/32649d74-7221-4ecf-83e6-f05c25eab91c)

**Comment by hyunicode** [comment]
It works fine, you should try updating
<img width="1512" alt="image" src="https://github.com/Astromations/Hazy/assets/81250265/47c49ccb-d317-4d18-8296-fa19d74a9669">
