### ISSUE TITLE
Don't Update Background

### ISSUE THREAD

**Issue by Fabian-MIA-23** [Astromations/Hazy#83]
I't wont update the background 
![image](https://github.com/Astromations/Hazy/assets/148222845/42d4f833-2884-4ce1-ad68-f3cace9f6c54)

**Comment by Fabian-MIA-23** [comment]
I am using default settings

Win 11
Ryzen 7 7700X
Asus ROG B650e F Gaming
32 GB DDR5
RTX 4070

**Comment by hbishere** [comment]
Probably related to #70.

**Comment by Astromations** [comment]
Do you mean your custom background image won't update, or the song album art doesn't update?

**Comment by Fabian-MIA-23** [comment]
Just Background

**Comment by Astromations** [comment]
Try using a link. Local images are sometimes too big.
