### ISSUE TITLE
i cant set a background

### ISSUE THREAD

**Issue by DiosaDuck** [Astromations/Hazy#84]
![imagen_2024-04-30_172642466](https://github.com/Astromations/Hazy/assets/161638609/55d27140-2860-4561-bed8-f8a4c5e09781)

i have installed spotify last version and spicetify aswell, but doesnt works

**Comment by Astromations** [comment]
Spotify's available memory is very volatile. Please upload the image to Imgur or some other online host, and use a link.

**Comment by DiosaDuck** [comment]
i did it already and nothing, theres really no fix?

**Comment by GuuVa** [comment]
> i did it already and nothing, theres really no fix?

Just right click any image and open the image in a new tab, copy that link and use it in settings. Selecting your own file seems to never work.

**Comment by Astromations** [comment]
> i did it already and nothing, theres really no fix?

Check if the image is a jpeg. If it is, try converting to a png and use a link to that instead.
