### ISSUE TITLE
Black backgrounds in areas

### ISSUE THREAD

**Issue by hbishere** [Astromations/Hazy#85]
Seen in the following areas:
- Artist Pages
- Search Results

![image](https://github.com/Astromations/Hazy/assets/108301517/cb7d7343-cd2e-4cbc-9322-ffbc604ac5b2)
![image](https://github.com/Astromations/Hazy/assets/108301517/304ebd05-b188-446c-ae9b-8ae4c0818177)

**Comment by hbishere** [comment]
Also seen in category pages.
![image](https://github.com/Astromations/Hazy/assets/108301517/5286bcc5-8600-406a-bc41-6d7741475e5e)

**Comment by SKDemon820** [comment]
Looks like a spicetify update changed a variable, you can fix it with this snippet temporarily

```
:root {
--spice-main: #0a0a0a00 !important
}
```
