### ISSUE TITLE
Editing the primary color

### ISSUE THREAD

**Issue by Noffelect** [Astromations/Hazy#86]
Is there any way to change the main color of the buttons? I tried to change it through the theme developer tool, but without success. The same green buttons. (30bf63)

**Comment by Astromations** [comment]
Any luck with the color.ini file perchance?

**Comment by Noffelect** [comment]
I don't know, I tried to replace the color 3 times, I also changed it in color.ini according to the manual, there were no changes...

**Comment by Noffelect** [comment]
![Spotify_J497LiFWd2](https://github.com/Astromations/Hazy/assets/158531587/252946f9-9239-4dd8-87a8-722ff8d3e93d)
To make it clearer

**Comment by Astromations** [comment]
It looks like I hard coded those colors, probably to get around some variable or other. You can change them directly in the css right here though:

![image](https://github.com/Astromations/Hazy/assets/80211195/2d75682f-067f-42dd-a843-7f06bfb25573)
