### ISSUE TITLE
Want be able to change background

### ISSUE THREAD

**Issue by abhi-d-7span** [Astromations/Hazy#87]
so i wend to edit and change my image to other from my device only not from web image and it want changing

**Comment by Astromations** [comment]
Sorry, I don't follow.

**Comment by hbishere** [comment]
Local images are very inconsistent. Try putting your image on an online host and then using it.

**Comment by abhi-d-7span** [comment]
> Local images are very inconsistent. Try putting your image on an online host and then using it.

yes currently I'm using that only
