### ISSUE TITLE
Add a song highlighter

### ISSUE THREAD

**Issue by thegoldknight** [Astromations/Hazy#9]
Hi, thanks for creating and maintaining this theme!
I think it would be really useful if you could implement a song highlighter that would indicate which song that is selected, since it's really hard to tell what is selected and especially so when highlighting multiple songs.

**Comment by Astromations** [comment]
Just added it! Thanks for the heads up. Didn't notice the indicator was so subtle. 

![image](https://github.com/Astromations/Hazy/assets/80211195/38f7d34e-c9e8-406b-82ed-4dc9f0caae80)

**Comment by thegoldknight** [comment]
Awesome, thanks!
