### ISSUE TITLE
Trying to set a .gif as background 

### ISSUE THREAD

**Issue by DoctorInfectious** [Astromations/Hazy#91]
The file plays fine in the preview windows but it won't allow me to apply some help or insight would be appreciated!

**Comment by hbishere** [comment]
Use a PNG or JPEG. GIFS are not supported by the player.

**Comment by Astromations** [comment]
I just tested this out with this gif ([link](https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif)). It should work. Make sure the link is hosted online and you're not trying to use a locally saved gif. The gif might also be particularly large and might take a minute to load.
