### ISSUE TITLE
Custom Background not working

### ISSUE THREAD

**Issue by Stormy-Fox** [Astromations/Hazy#92]
The custom background feature has stopped working. After my PC restarted I was met with a black background. I tried to re apply my background and was met with the same black background. I have tried using a different link and even tried downloading the image and applying it that way too no luck.

I have tried the usual uninstall and reinstall and also have tried re installing spicetify itself. Neither of witch options have fixed the issue.

I have the latest version of spicetify and marketplace.

**Comment by Astromations** [comment]
Try playing a song. Sometimes the Javascript to set the background doesn't run unless a song is played.

**Comment by Astromations** [comment]
I'm not sure what fixes you've attempted exactly, so just for redundancy sake do the following: 

1. Run 'spicetify backup apply'

2. Run 'spicetify update'

3. Click on the three dots in the top left > Help > About Spotify > send a screenshot of the resulting pop up. This is the latest non-windows-store version: [link](https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.38.720.ga4a70a0e-1223.exe)

4. If you don't mind, send the link you're trying to use

5. See if the regular Album Art Background works

I'm struggling to replicate the issue on my end.

**Comment by Stormy-Fox** [comment]
![Screenshot_171](https://github.com/Astromations/Hazy/assets/170465563/32488b6e-2926-4996-87e0-5957fdc35edb)
![Screenshot_170](https://github.com/Astromations/Hazy/assets/170465563/82e90fa3-a76b-44d2-9dc2-8e70363ee9c2)
![Screenshot_169](https://github.com/Astromations/Hazy/assets/170465563/a5050c7c-cef4-47eb-b2ff-64e31f90e4c2)

I have attached some screenshots, the "about Spotify popup", a Screenshot while trying to apply the custom background and a screenshot without. It would appear that is is just the custom background feature as the album art background does seem to work.

I have tried many different image links with different formats and have also tried to download some images and apply it that way. My Spicetify is fully up to date.

**Comment by Donaldino7712** [comment]
This seems to work fine for me. Have you tried changing the link of the photo? The default one ([this](https://elmina.club/uploads/posts/2023-05/1684477431_elmina-club-p-uyutnii-fon-dlya-rabochego-stola-foni-pint-52.png)) is unavailable now.

**Comment by Astromations** [comment]
Any updates? Have you tried any other image links?

**Comment by RustyVIV** [comment]
I had the same problem, I only managed to solve it for the links by putting ".jpg" at the end of the URL and only with the "imgur" site.
