### ISSUE TITLE
now playing view is opaque

### ISSUE THREAD

**Issue by snadwich01** [Astromations/Hazy#96]
![image_2024-05-26_203859087](https://github.com/Astromations/Hazy/assets/79296594/eb5950c7-f723-40a0-b17d-2ac340a34e74)
recently after the update the now playing view has turned opaque, with the colour depending on the soundtrack art, instead of how it used to be translucent before so i could see the wallpaper behind the album art and stuff

**Comment by Astromations** [comment]
Fixed in the latest commit
