### ISSUE TITLE
Offset and overlaping buttons. Causes them not to work (Marketplace and statistic page only)

### ISSUE THREAD

**Issue by Corp01937** [Astromations/Hazy#97]
Marketplace page:
![image](https://github.com/Astromations/Hazy/assets/96797729/a915460f-adc1-4a70-a7ce-abb7f97aa16f)
Satistics app page:
![image](https://github.com/Astromations/Hazy/assets/96797729/0988715b-b085-4b05-a976-d9207cacaf2e)

Some of the buttons in the market place and the statistics app are overlaping and offset. Some buttons including the settings no longer work (theme can still be uninstalled fine).

I am on a windows 10 computer.
Latest build of both spotify (direct not windows store) and spicetfy.

This is the only place i have found the issue.

This bug does not happen when the theme is uninstalled. However with the theme uninstalled it does happen for a second or two then is aligned above the sort by option and all buttons work. Dont know if this helps.

Love the look of the entire theme. Some amazing work!!

[Edit] Forgot to put in the image for the stats page. Its there now.

**Comment by Astromations** [comment]
Do you have any other Extensions or Custom Apps installed?

**Comment by Corp01937** [comment]
No other apps installed. I do have some extensions installed but none of them are affecting the top half of the graphical interface only the lower bar part were volume and album art is displayed.

**Comment by Corp01937** [comment]
![image](https://github.com/Astromations/Hazy/assets/96797729/32b91467-d638-4b25-ae14-085a6f48a735)
Here is an image with nothing installed except Hazey and Stats

**Comment by Corp01937** [comment]
This is nothing installed but the Theme
![image](https://github.com/Astromations/Hazy/assets/96797729/5ae23677-a21c-4b38-8e65-faf79626d418)

**Comment by Astromations** [comment]
That can't be. Spotify does not look like that unless modded. You should have a Navbar, and your search bar should not be up there. At the very least it's a setting or Experimental Feature that maybe I'm not aware of, but Spotify looks like this by default:
![image](https://github.com/Astromations/Hazy/assets/80211195/665eb694-7354-4b60-aeaf-c6a4148a4075)

I vaguely remember some mod or snippet or other that I've seen before that makes the UI look as it does in your screenshot. I'll look for it, but you almost definitely had something other than the theme installed in that screenshot.

**Comment by Corp01937** [comment]
Ok thanks for the information i will manualy delete all spotify files and see if it will work then.

**Comment by Astromations** [comment]
Wait! Found it! It's an Experimental Feature!

![image](https://github.com/Astromations/Hazy/assets/80211195/0d81ca01-72d6-4ea1-9cd9-430f46c331c2)

Set it to control! No need to wipe your Spotify.

**Comment by Astromations** [comment]
No problem. Have a good one 👍
