### ISSUE TITLE
blocking marketplace

### ISSUE THREAD

**Issue by RenDaemon** [Astromations/Hazy#98]
![image](https://github.com/Astromations/Hazy/assets/94961661/01c0b9fe-522c-4fad-8cd8-e5e2c0a9688f)

**Comment by angelmora2004** [comment]
same problem
![image](https://github.com/Astromations/Hazy/assets/105449326/a847971a-6f84-4b06-96e1-c3330c8907ae)

**Comment by angelmora2004** [comment]
Spotify for Windows (64 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
Theme: Hazy / Base
Custom apps: marketplace

**Comment by RenDaemon** [comment]
Spotify for Windows (64 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
Theme: Hazy / Comfy
Extensions: comfy.js, adblock.js
Custom apps: marketplace, lyrics-plus

**Comment by angelmora2004** [comment]
We've the same version

**Comment by Astromations** [comment]
Could you send a screenshot of the full window?

**Comment by RenDaemon** [comment]
![image](https://github.com/Astromations/Hazy/assets/94961661/dc85aa50-db13-4b53-9cb7-10de87f31947)

**Comment by sanoojes** [comment]
this is caused when the marketplace header is fixed 
![image](https://github.com/Astromations/Hazy/assets/93819264/b398cd40-c9db-41c9-ac6e-7bb62d050654)

**Comment by Astromations** [comment]
I think it's the same for static. I set it back to relative. It's default. Please check back if that fixed it.

**Comment by Astromations** [comment]
Found out it might be due to an out of date Marketplace. Please run this command in powershell:

```Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.ps1" | Invoke-Expression```

**Comment by angelmora2004** [comment]
Thank u bro it works :D

**Comment by RenDaemon** [comment]
it's works as before bro, thank you
